# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: gogoproto/gogo.proto
# plugin: python-betterproto
# This file has been @generated

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from dataclasses import dataclass
else:
    from pydantic.dataclasses import dataclass

import betterproto
