# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: greenfield/resource/types.proto
# plugin: python-betterproto
# This file has been @generated
from dataclasses import dataclass

import betterproto


class ResourceType(betterproto.Enum):
    RESOURCE_TYPE_UNSPECIFIED = 0
    RESOURCE_TYPE_BUCKET = 1
    RESOURCE_TYPE_OBJECT = 2
    RESOURCE_TYPE_GROUP = 3
