# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: tendermint/services/pruning/v1/pruning.proto, tendermint/services/pruning/v1/service.proto
# plugin: python-betterproto
# This file has been @generated
from dataclasses import dataclass
from typing import TYPE_CHECKING, Dict, Optional

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase

if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


@dataclass(eq=False, repr=False)
class SetBlockRetainHeightRequest(betterproto.Message):
    height: int = betterproto.uint64_field(1)


@dataclass(eq=False, repr=False)
class SetBlockRetainHeightResponse(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class GetBlockRetainHeightRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class GetBlockRetainHeightResponse(betterproto.Message):
    app_retain_height: int = betterproto.uint64_field(1)
    """The retain height set by the application."""

    pruning_service_retain_height: int = betterproto.uint64_field(2)
    """
    The retain height set via the pruning service (e.g. by the data
    companion) specifically for blocks.
    """


@dataclass(eq=False, repr=False)
class SetBlockResultsRetainHeightRequest(betterproto.Message):
    height: int = betterproto.uint64_field(1)


@dataclass(eq=False, repr=False)
class SetBlockResultsRetainHeightResponse(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class GetBlockResultsRetainHeightRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class GetBlockResultsRetainHeightResponse(betterproto.Message):
    pruning_service_retain_height: int = betterproto.uint64_field(1)
    """
    The retain height set by the pruning service (e.g. by the data
    companion) specifically for block results.
    """


@dataclass(eq=False, repr=False)
class SetTxIndexerRetainHeightRequest(betterproto.Message):
    height: int = betterproto.uint64_field(1)


@dataclass(eq=False, repr=False)
class SetTxIndexerRetainHeightResponse(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class GetTxIndexerRetainHeightRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class GetTxIndexerRetainHeightResponse(betterproto.Message):
    height: int = betterproto.uint64_field(1)


@dataclass(eq=False, repr=False)
class SetBlockIndexerRetainHeightRequest(betterproto.Message):
    height: int = betterproto.uint64_field(1)


@dataclass(eq=False, repr=False)
class SetBlockIndexerRetainHeightResponse(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class GetBlockIndexerRetainHeightRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class GetBlockIndexerRetainHeightResponse(betterproto.Message):
    height: int = betterproto.uint64_field(1)


class PruningServiceStub(betterproto.ServiceStub):
    async def set_block_retain_height(
        self,
        set_block_retain_height_request: "SetBlockRetainHeightRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "SetBlockRetainHeightResponse":
        return await self._unary_unary(
            "/tendermint.services.pruning.v1.PruningService/SetBlockRetainHeight",
            set_block_retain_height_request,
            SetBlockRetainHeightResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_block_retain_height(
        self,
        get_block_retain_height_request: "GetBlockRetainHeightRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "GetBlockRetainHeightResponse":
        return await self._unary_unary(
            "/tendermint.services.pruning.v1.PruningService/GetBlockRetainHeight",
            get_block_retain_height_request,
            GetBlockRetainHeightResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def set_block_results_retain_height(
        self,
        set_block_results_retain_height_request: "SetBlockResultsRetainHeightRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "SetBlockResultsRetainHeightResponse":
        return await self._unary_unary(
            "/tendermint.services.pruning.v1.PruningService/SetBlockResultsRetainHeight",
            set_block_results_retain_height_request,
            SetBlockResultsRetainHeightResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_block_results_retain_height(
        self,
        get_block_results_retain_height_request: "GetBlockResultsRetainHeightRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "GetBlockResultsRetainHeightResponse":
        return await self._unary_unary(
            "/tendermint.services.pruning.v1.PruningService/GetBlockResultsRetainHeight",
            get_block_results_retain_height_request,
            GetBlockResultsRetainHeightResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def set_tx_indexer_retain_height(
        self,
        set_tx_indexer_retain_height_request: "SetTxIndexerRetainHeightRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "SetTxIndexerRetainHeightResponse":
        return await self._unary_unary(
            "/tendermint.services.pruning.v1.PruningService/SetTxIndexerRetainHeight",
            set_tx_indexer_retain_height_request,
            SetTxIndexerRetainHeightResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_tx_indexer_retain_height(
        self,
        get_tx_indexer_retain_height_request: "GetTxIndexerRetainHeightRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "GetTxIndexerRetainHeightResponse":
        return await self._unary_unary(
            "/tendermint.services.pruning.v1.PruningService/GetTxIndexerRetainHeight",
            get_tx_indexer_retain_height_request,
            GetTxIndexerRetainHeightResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def set_block_indexer_retain_height(
        self,
        set_block_indexer_retain_height_request: "SetBlockIndexerRetainHeightRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "SetBlockIndexerRetainHeightResponse":
        return await self._unary_unary(
            "/tendermint.services.pruning.v1.PruningService/SetBlockIndexerRetainHeight",
            set_block_indexer_retain_height_request,
            SetBlockIndexerRetainHeightResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_block_indexer_retain_height(
        self,
        get_block_indexer_retain_height_request: "GetBlockIndexerRetainHeightRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "GetBlockIndexerRetainHeightResponse":
        return await self._unary_unary(
            "/tendermint.services.pruning.v1.PruningService/GetBlockIndexerRetainHeight",
            get_block_indexer_retain_height_request,
            GetBlockIndexerRetainHeightResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class PruningServiceBase(ServiceBase):
    async def set_block_retain_height(
        self, set_block_retain_height_request: "SetBlockRetainHeightRequest"
    ) -> "SetBlockRetainHeightResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_block_retain_height(
        self, get_block_retain_height_request: "GetBlockRetainHeightRequest"
    ) -> "GetBlockRetainHeightResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def set_block_results_retain_height(
        self,
        set_block_results_retain_height_request: "SetBlockResultsRetainHeightRequest",
    ) -> "SetBlockResultsRetainHeightResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_block_results_retain_height(
        self,
        get_block_results_retain_height_request: "GetBlockResultsRetainHeightRequest",
    ) -> "GetBlockResultsRetainHeightResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def set_tx_indexer_retain_height(
        self, set_tx_indexer_retain_height_request: "SetTxIndexerRetainHeightRequest"
    ) -> "SetTxIndexerRetainHeightResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_tx_indexer_retain_height(
        self, get_tx_indexer_retain_height_request: "GetTxIndexerRetainHeightRequest"
    ) -> "GetTxIndexerRetainHeightResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def set_block_indexer_retain_height(
        self,
        set_block_indexer_retain_height_request: "SetBlockIndexerRetainHeightRequest",
    ) -> "SetBlockIndexerRetainHeightResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_block_indexer_retain_height(
        self,
        get_block_indexer_retain_height_request: "GetBlockIndexerRetainHeightRequest",
    ) -> "GetBlockIndexerRetainHeightResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_set_block_retain_height(
        self,
        stream: "grpclib.server.Stream[SetBlockRetainHeightRequest, SetBlockRetainHeightResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.set_block_retain_height(request)
        await stream.send_message(response)

    async def __rpc_get_block_retain_height(
        self,
        stream: "grpclib.server.Stream[GetBlockRetainHeightRequest, GetBlockRetainHeightResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_block_retain_height(request)
        await stream.send_message(response)

    async def __rpc_set_block_results_retain_height(
        self,
        stream: "grpclib.server.Stream[SetBlockResultsRetainHeightRequest, SetBlockResultsRetainHeightResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.set_block_results_retain_height(request)
        await stream.send_message(response)

    async def __rpc_get_block_results_retain_height(
        self,
        stream: "grpclib.server.Stream[GetBlockResultsRetainHeightRequest, GetBlockResultsRetainHeightResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_block_results_retain_height(request)
        await stream.send_message(response)

    async def __rpc_set_tx_indexer_retain_height(
        self,
        stream: "grpclib.server.Stream[SetTxIndexerRetainHeightRequest, SetTxIndexerRetainHeightResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.set_tx_indexer_retain_height(request)
        await stream.send_message(response)

    async def __rpc_get_tx_indexer_retain_height(
        self,
        stream: "grpclib.server.Stream[GetTxIndexerRetainHeightRequest, GetTxIndexerRetainHeightResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_tx_indexer_retain_height(request)
        await stream.send_message(response)

    async def __rpc_set_block_indexer_retain_height(
        self,
        stream: "grpclib.server.Stream[SetBlockIndexerRetainHeightRequest, SetBlockIndexerRetainHeightResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.set_block_indexer_retain_height(request)
        await stream.send_message(response)

    async def __rpc_get_block_indexer_retain_height(
        self,
        stream: "grpclib.server.Stream[GetBlockIndexerRetainHeightRequest, GetBlockIndexerRetainHeightResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_block_indexer_retain_height(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/tendermint.services.pruning.v1.PruningService/SetBlockRetainHeight": grpclib.const.Handler(
                self.__rpc_set_block_retain_height,
                grpclib.const.Cardinality.UNARY_UNARY,
                SetBlockRetainHeightRequest,
                SetBlockRetainHeightResponse,
            ),
            "/tendermint.services.pruning.v1.PruningService/GetBlockRetainHeight": grpclib.const.Handler(
                self.__rpc_get_block_retain_height,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetBlockRetainHeightRequest,
                GetBlockRetainHeightResponse,
            ),
            "/tendermint.services.pruning.v1.PruningService/SetBlockResultsRetainHeight": grpclib.const.Handler(
                self.__rpc_set_block_results_retain_height,
                grpclib.const.Cardinality.UNARY_UNARY,
                SetBlockResultsRetainHeightRequest,
                SetBlockResultsRetainHeightResponse,
            ),
            "/tendermint.services.pruning.v1.PruningService/GetBlockResultsRetainHeight": grpclib.const.Handler(
                self.__rpc_get_block_results_retain_height,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetBlockResultsRetainHeightRequest,
                GetBlockResultsRetainHeightResponse,
            ),
            "/tendermint.services.pruning.v1.PruningService/SetTxIndexerRetainHeight": grpclib.const.Handler(
                self.__rpc_set_tx_indexer_retain_height,
                grpclib.const.Cardinality.UNARY_UNARY,
                SetTxIndexerRetainHeightRequest,
                SetTxIndexerRetainHeightResponse,
            ),
            "/tendermint.services.pruning.v1.PruningService/GetTxIndexerRetainHeight": grpclib.const.Handler(
                self.__rpc_get_tx_indexer_retain_height,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetTxIndexerRetainHeightRequest,
                GetTxIndexerRetainHeightResponse,
            ),
            "/tendermint.services.pruning.v1.PruningService/SetBlockIndexerRetainHeight": grpclib.const.Handler(
                self.__rpc_set_block_indexer_retain_height,
                grpclib.const.Cardinality.UNARY_UNARY,
                SetBlockIndexerRetainHeightRequest,
                SetBlockIndexerRetainHeightResponse,
            ),
            "/tendermint.services.pruning.v1.PruningService/GetBlockIndexerRetainHeight": grpclib.const.Handler(
                self.__rpc_get_block_indexer_retain_height,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetBlockIndexerRetainHeightRequest,
                GetBlockIndexerRetainHeightResponse,
            ),
        }
