# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: tendermint/votepool/types.proto
# plugin: python-betterproto
# This file has been @generated
from dataclasses import dataclass

import betterproto


@dataclass(eq=False, repr=False)
class Vote(betterproto.Message):
    pub_key: bytes = betterproto.bytes_field(1)
    signature: bytes = betterproto.bytes_field(2)
    event_type: int = betterproto.uint32_field(3)
    event_hash: bytes = betterproto.bytes_field(4)


@dataclass(eq=False, repr=False)
class Message(betterproto.Message):
    vote: "Vote" = betterproto.message_field(1, group="sum")
