# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: cosmos/oracle/module/v1/module.proto
# plugin: python-betterproto
# This file has been @generated

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from dataclasses import dataclass
else:
    from pydantic.dataclasses import dataclass

import betterproto


@dataclass(eq=False, repr=False)
class Module(betterproto.Message):
    """Module is the config object of the oracle module."""

    fee_collector_name: str = betterproto.string_field(2)
    """fee_collector_name is the name of the FeeCollector ModuleAccount."""

    authority: str = betterproto.string_field(3)
    """
    authority defines the custom module authority. If not set, defaults to the
    governance module.
    """
