# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: cosmos/crypto/eth/bls/keys.proto
# plugin: python-betterproto
# This file has been @generated

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from dataclasses import dataclass
else:
    from pydantic.dataclasses import dataclass

import betterproto


@dataclass(eq=False, repr=False)
class PubKey(betterproto.Message):
    """
    PubKey defines a bls public key Key is the compressed form of the pubkey.
    """

    key: bytes = betterproto.bytes_field(1)
    """key is the public key in byte form"""


@dataclass(eq=False, repr=False)
class PrivKey(betterproto.Message):
    """PrivKey defines a bls private key."""

    key: bytes = betterproto.bytes_field(1)
    """key is the private key in byte form"""
